### ISSUE TITLE
problem with interap TimerOne

### ISSUE THREAD

**Issue by gunaone** [vanbwodonk/Gelatino#2]
i have problem with error in enterup..
did u now what the problem?
i use arduino IDE 1.6.4
error : 
In file included from ari_ndari_inverter.ino:2:0:
C:\Users\guna_on3\Documents\Arduino\libraries\TimerOne-master/TimerOne.h: In member function 'void TimerOne::setPwmDuty(char, unsigned int)':
C:\Users\guna_on3\Documents\Arduino\libraries\TimerOne-master/TimerOne.h:105:13: error: 'TIMER1_A_PIN' was not declared in this scope
  if (pin == TIMER1_A_PIN) OCR1A = dutyCycle;
             ^
C:\Users\guna_on3\Documents\Arduino\libraries\TimerOne-master/TimerOne.h: In member function 'void TimerOne::pwm(char, unsigned int)':
C:\Users\guna_on3\Documents\Arduino\libraries\TimerOne-master/TimerOne.h:114:13: error: 'TIMER1_A_PIN' was not declared in this scope
  if (pin == TIMER1_A_PIN) { pinMode(TIMER1_A_PIN, OUTPUT); TCCR1A |= _BV(COM1A1); }
             ^
C:\Users\guna_on3\Documents\Arduino\libraries\TimerOne-master/TimerOne.h: In member function 'void TimerOne::disablePwm(char)':
C:\Users\guna_on3\Documents\Arduino\libraries\TimerOne-master/TimerOne.h:129:13: error: 'TIMER1_A_PIN' was not declared in this scope
  if (pin == TIMER1_A_PIN) TCCR1A &= ~_BV(COM1A1);
             ^
C:\Users\guna_on3\Documents\Arduino\libraries\TimerOne-master/TimerOne.h: In member function 'void TimerOne::attachInterrupt(void (*)())':
C:\Users\guna_on3\Documents\Arduino\libraries\TimerOne-master/TimerOne.h:143:2: error: 'TIMSK1' was not declared in this scope
  TIMSK1 = _BV(TOIE1);
  ^
C:\Users\guna_on3\Documents\Arduino\libraries\TimerOne-master/TimerOne.h: In member function 'void TimerOne::detachInterrupt()':
C:\Users\guna_on3\Documents\Arduino\libraries\TimerOne-master/TimerOne.h:150:2: error: 'TIMSK1' was not declared in this scope
  TIMSK1 = 0;
  ^
Error compiling.

**Comment by vanbwodonk** [comment]
Usually need compatibility patch for arduino library, what avr do you use?

**Comment by vanbwodonk** [comment]
closed during inactive,

**Comment by fire1** [comment]
Atmega8
